# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 03:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0106_auto_20210113_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='property_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='districtproposal',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercialoperator_district_proposals_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
